name = "Vinyl"
grammar = "vinyl"
path_suffixes = ["vn"]
line_comments = ["# "]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])>"
tab_size = 4
word_characters = ["_"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]