use tower_lsp::lsp_types::CompletionItemKind;

pub const KEYWORDS: &[(&str, CompletionItemKind)] = &[
    ("fn", CompletionItemKind::KEYWORD),
    ("let", CompletionItemKind::KEYWORD),
    ("mut", CompletionItemKind::KEYWORD),
    ("return", CompletionItemKind::KEYWORD),
    ("if", CompletionItemKind::KEYWORD),
    ("else", CompletionItemKind::KEYWORD),
    ("match", CompletionItemKind::KEYWORD),
    ("while", CompletionItemKind::KEYWORD),
    ("loop", CompletionItemKind::KEYWORD),
    ("break", CompletionItemKind::KEYWORD),
    ("continue", CompletionItemKind::KEYWORD),
    ("import", CompletionItemKind::KEYWORD),
    ("public", CompletionItemKind::KEYWORD),
    ("true", CompletionItemKind::KEYWORD),
    ("false", CompletionItemKind::KEYWORD),
    ("unit", CompletionItemKind::KEYWORD),
    ("not", CompletionItemKind::KEYWORD),
    ("and", CompletionItemKind::KEYWORD),
    ("or", CompletionItemKind::KEYWORD),
    ("struct", CompletionItemKind::KEYWORD),
    ("enum", CompletionItemKind::KEYWORD),
    ("tuple", CompletionItemKind::KEYWORD),
    ("type", CompletionItemKind::KEYWORD),
    ("int", CompletionItemKind::KEYWORD),
    ("float", CompletionItemKind::KEYWORD),
    ("bool", CompletionItemKind::KEYWORD),
    ("char", CompletionItemKind::KEYWORD),
    ("string", CompletionItemKind::KEYWORD),
    ("int8", CompletionItemKind::KEYWORD),
    ("int16", CompletionItemKind::KEYWORD),
    ("int32", CompletionItemKind::KEYWORD),
    ("int64", CompletionItemKind::KEYWORD),
    ("int128", CompletionItemKind::KEYWORD),
    ("isize", CompletionItemKind::KEYWORD),
    ("uint8", CompletionItemKind::KEYWORD),
    ("uint16", CompletionItemKind::KEYWORD),
    ("uint32", CompletionItemKind::KEYWORD),
    ("uint64", CompletionItemKind::KEYWORD),
    ("uint128", CompletionItemKind::KEYWORD),
    ("usize", CompletionItemKind::KEYWORD),
    ("float32", CompletionItemKind::KEYWORD),
    ("float64", CompletionItemKind::KEYWORD),
];

pub const MODULE_PREFIXES: &[(&str, CompletionItemKind)] = &[
    ("self::", CompletionItemKind::KEYWORD),
    ("parent::", CompletionItemKind::KEYWORD),
    ("package::", CompletionItemKind::KEYWORD),
];
