[package]
name = "vinyl-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
vinyl-typecheck = { path = "../typecheck" }
vinyl-parser = { path = "../parser" }
cranelift-jit = "0.133.1"
cranelift-module = "0.133.1"
cranelift-codegen = "0.133.1"
cranelift-frontend = "0.133.1"
target-lexicon = "0.13.5"
tracing = "0.1"
